# Part A #



    1. min
    2. max
    3. mean
    4. argmin
    5. argmax
    6. linalg.solve
    7. flatten
    8. ravel
    9. dot Product
    10. * for Matrix (Element wise multiplication)
    11. arange followed by reshape
    12. identity / eye
    13. sum
    14. diag
    15. tril /triu
    

In [195]:
import numpy as np

In [196]:
a = (np.arange(1, 10) ** 2).reshape(3, 3)
a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

#### Minimum Value ####

In [197]:
min_value = a.min()

#### Maximum Value ####

In [198]:
max_value = a.max()

#### Mean Value ####

In [199]:
mean_value = a.mean()

#### Minimum Argument Value ####

In [200]:
argmin_value = a.argmin()

#### Maxmimum Agrument Value ####

In [201]:
argmin_value = a.argmax()

In [202]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c = np.array([10, 11, 12])
d = np.array([[13, 14, 15], [16, 17, 18], [19, 20, 21]])

#### Line argument eqution solution ####

In [203]:
solve = np.linalg.solve(b, c)
solve

array([  2.26666667, -13.53333333,  11.6       ])

#### Making a 2D into 1D array using flattern ####

In [204]:
flat = b.flatten()

#### Making a 2D into 1D array using ravel ####

In [205]:
ravel = b.ravel()

#### Dot product of two matrix ####

In [206]:
dot_product = np.dot(b, d)
dot_product

array([[102, 108, 114],
       [246, 261, 276],
       [390, 414, 438]])

#### Multipling two matrix ####

In [207]:
multiply = np.multiply(b, d)

#### Creating an array with arrange and then using Reshape ####

In [208]:
reshaped_array=np.arange(10).reshape(2, 5)

#### Creating a identity matrix ####

In [209]:
identty_matrix = np.identity(4)

#### adding values of element ####

In [210]:
add = np.sum(b)

#### finding all the diagonal elements ####

In [211]:
diagonal = np.diag(d)

#### Lower triangular Matrix ####

In [212]:
Lower_tri = np.tril(b)

#### Upper triangular Matrix ####

In [213]:
Upper_tri = np.triu(b)

# Part B #

#### Mimimun Value ####

In [214]:
minn = a[0][0]
for i in list(range(a.shape[0])):
    for j in list(range(a.shape[1])):
        if (a[i][j] <= minn):
            minn = a[i][j]

#### Maximum Value ####

In [215]:
maxx = a[0][0]
for i in list(range(a.shape[0])):
    for j in list(range(a.shape[1])):
        if (a[i][j] >= maxx):
            maxx = a[i][j]

#### Mean Value ####

In [216]:
meen = 0
for i in list(range(a.shape[0])):
    for j in list(range(a.shape[1])):
        meen = meen + a[i][j]
meen/a.size

31.666666666666668

#### Minimum Argument Value ####

In [217]:
argmin =0
index =0
minn= a[0][0]
for i in list(range(a.shape[0])):
    for j in list(range(a.shape[1])):
        if (a[i][j] <= minn):
            minn = a[i][j]
            argmin = index
        index += 1

#### Maxmimum Agrument Value ####

In [218]:
argmax = 0
index = 0
maxx = a[0][0]
for i in list(range(a.shape[0])):
    for j in list(range(a.shape[1])):
        if (a[i][j] >= maxx):
            maxx = a[i][j]
            argmax = index
        index += 1

#### Flattering and ravel ####

In [219]:
arr = []
for i in list(range(a.shape[0])):
    for j in list(range(a.shape[1])):
        arr.append(a[i][j])

#### Reshaping the array ####

In [235]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
row= 3
column= 4
count=0
reshaped_arr =[]
for i in range(row):
    w=[]
    for j in range(column):
        w.append(array[count])
        count += 1
    reshaped_arr.append(w)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

#### Dot product of two matrix ####

In [220]:
arr_dot = np.empty([3, 3])
for i in list(range(b.shape[0])):
    for j in list(range(b.shape[1])):
        s = 0
        for k in list(range(d.shape[0])):
            s = s + ((b[i][k]) * (d[k][j]))
        arr_dot[i][j] = s

#### Multipling two matrix ####

In [221]:
arr_multi = np.empty([3, 3])
for i in list(range(b.shape[0])):
    for j in list(range(b.shape[1])):
        arr_multi[i][j] = b[i][j] * d[i][j]

#### Creating a identity matrix ####

In [222]:
iden = np.empty([3, 3])
for i in list(range(iden.shape[0])):
    for j in list(range(iden.shape[1])):
        if(i == j):
            iden[i][j] = 1
        else:
            iden[i][j] = 0

#### adding values of element ####

In [223]:
sum = 0
for i in list(range(b.shape[0])):
    for j in list(range(b.shape[1])):
        sum = sum + b[i][j]

#### finding all the diagonal elements ####

In [230]:
diag = []
if (b.shape[0] == b.shape[1]):
    for i in list(range(b.shape[0])):
        for j in list(range(b.shape[1])):
            if i == j:
                diag.append(b[i][j])
else:
    print "Error"

#### Lower triangular Matrix ####

In [225]:
lower_trin = np.empty([b.shape[0], b.shape[1]])
for i in list(range(b.shape[0])):
    for j in list(range(b.shape[1])):
        if (i < j):
            lower_trin[i][j] = 0
        else:
            lower_trin[i][j] = b[i][j]

#### Upper triangular Matrix ####

In [228]:
upper_trin = np.empty([d.shape[0], d.shape[1]])
for i in list(range(d.shape[0])):
    for j in list(range(d.shape[1])):
        if (i > j):
            upper_trin[i][j] = 0
        else:
            upper_trin[i][j] = d[i][j]